# Generated by Django 5.2.13 on 2026-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
